Task 2
Perfectrum/formal-lang-course pull request #3
Opened 2023-03-05 20:15 UTC by Perfectrum

- [x] Используя возможности [pyformlang](https://pyformlang.readthedocs.io/en/latest/) реализовать **функцию** построения минимального ДКА по заданному регулярному выражению. [Формат регулярного выражения.](https://pyformlang.readthedocs.io/en/latest/usage.html#regular-expression).
- [x] Используя возможности [pyformlang](https://pyformlang.readthedocs.io/en/latest/) реализовать **функцию** построения недетерминированного конечного автомата по [графу](https://networkx.org/documentation/stable/reference/classes/multidigraph.html), в том числе по любому из графов, которые можно получить, пользуясь функциональностью, реализованной в [Задаче 1](https://github.com/FormalLanguageConstrainedPathQuerying/formal-lang-course/blob/main/tasks/task1.md) (загруженный из набора данных по имени граф, сгенерированный синтетический граф). Предусмотреть возможность указывать стартовые и финальные вершины. Если они не указаны, то считать все вершины стартовыми и финальными.
- [x] Добавить необходимые тесты.

2023-03-06 06:54 UTC, rustam-azimov requested changes

2023-03-06 06:54 UTC, rustam-azimov commented on project/fa_utils.py
> +def regex2dfa(regex: str) -> DeterministicFiniteAutomaton:
Теперь пишите пожалуйста ко всем функциям докстринги

2023-03-06 11:09 UTC, Perfectrum commented
Так? А нужны ли докстринги для тестов?

2023-03-07 07:40 UTC, rustam-azimov commented
Для тестов не нужны

2023-03-07 07:40 UTC, rustam-azimov approved these changes

2023-03-09 21:15 UTC, merged